# Configuration for mutation and fixing behavior

mutation:
  # Probability of each mutation type
  probabilities:
    line: 0.5        # Delete a single line
    block: 0.3       # Delete a code block
    function: 0.15   # Delete an entire function
    file: 0.05       # Delete an entire file

  # Damage levels
  damage_level: "medium"  # low, medium, high

  # Random seed (null for random, or set for reproducibility)
  seed: null

fixer:
  # LLM configuration
  model: "gpt-3.5-turbo"  # Use non-cutting-edge model
  temperature: 0.7
  max_tokens: 2000
