name: Mutation Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - test-main

permissions:
  contents: write
  pull-requests: write

jobs:
  pipeline:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'test-mutation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Bodybuilders[bot]"
          git config user.email "bodybuilders[bot]@bodybuilders.com"

      - name: Merge test-main into test-mutation
        run: |
          git checkout test-mutation
          git merge test-main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scripts/mutator.py
        run: python scripts/mutator.py

      - name: Run scripts/fixer.py
        run: python scripts/fixer.py

      - name: Create Pull Request to test-main
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: test-main
          branch-suffix: timestamp
          title: "Bodybuilder PR: Test-Mutation → Test-Main"
          committer: "Bodybuilder[Bot] <bodybuilders@bodybuilders.com>"
          author: "Bodybuilders[Bot] <bodybuilders@bodybuilders.com>"
          body: |
            This PR was automatically created after running mutator.py and fixer.py.
          delete-branch: false

      - name: Output PR info
        run: |
          echo "PR number: ${{ steps.pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.pr.outputs.pull-request-url }}"
