name: Mutation Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  pipeline:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'mutation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Bodybuilders[bot]"
          git config user.email "bodybuilders[bot]@bodybuilders.com"

      - name: Check if branch exists, if not create it
        run: |
          BRANCH_NAME="mutation"

          echo "Checking if branch '$BRANCH_NAME' exists..."

          if git ls-remote --heads origin "$BRANCH_NAME" | grep "$BRANCH_NAME" >/dev/null; then
            echo "Branch '$BRANCH_NAME' already exists in origin."
            git fetch origin "$BRANCH_NAME"
          else
            echo "Branch '$BRANCH_NAME' does not exist. Creating it..."
            git fetch origin main
            git checkout -b "$BRANCH_NAME" origin/main
            git push origin "$BRANCH_NAME"
            echo "Branch '$BRANCH_NAME' created and pushed."
          fi

      - name: Rebase main into mutation
        run: |
          set -e
          BRANCH_NAME="mutation"
          BASE_BRANCH="main"

          echo "Fetching branches..."
          git fetch origin $BASE_BRANCH
          git fetch origin $BRANCH_NAME || echo "Remote branch $BRANCH_NAME does not exist yet"

          # Ensure local base branch exists
          if ! git show-ref --verify --quiet "refs/heads/$BASE_BRANCH"; then
            git checkout -b "$BASE_BRANCH" "origin/$BASE_BRANCH"
          else
            git checkout "$BASE_BRANCH"
            git reset --hard "origin/$BASE_BRANCH"
          fi

          # Ensure local mutation branch exists
          if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
            echo "Local branch $BRANCH_NAME exists"
            git checkout "$BRANCH_NAME"
          elif git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            echo "Remote branch $BRANCH_NAME exists, creating local tracking branch"
            git checkout -b "$BRANCH_NAME" "origin/$BRANCH_NAME"
          else
            echo "Branch $BRANCH_NAME does not exist at all. Creating from $BASE_BRANCH"
            git checkout -b "$BRANCH_NAME" "origin/$BASE_BRANCH"
            git push origin "$BRANCH_NAME"
          fi

          echo "Rebasing $BRANCH_NAME onto $BASE_BRANCH..."
          git rebase "origin/$BASE_BRANCH" || { echo "Rebase failed"; exit 1; }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scripts/mutator.py
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python scripts/mutator.py medium

      - name: Run scripts/fixer.py
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python scripts/fixer.py

      - name: Capture mutation context
        id: capture
        run: |
          MUTATION_OUTPUT=$(cat mutation-context.json)
          echo "mutation_output<<EOF" >> $GITHUB_OUTPUT
          echo "$MUTATION_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Summarize mutation context
        id: summary
        run: |
          SUMMARY=$(jq -r '
            "Timestamp: \(.timestamp)\nMutation ID: \(.mutation_id)\nFlavor: \(.config.flavor)\nMutated Files:\n" +
            (.mutations[] | "  - \(.file) lines \(.start_line)–\(.start_line + .deleted_line_count - 1)")
          ' mutation-context.json)
          echo "mutation_summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request to main
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: mutation
          title: "Bodybuilder PR: Mutation → Main"
          committer: "Bodybuilder[Bot] <bodybuilders@bodybuilders.com>"
          author: "Bodybuilders[Bot] <bodybuilders@bodybuilders.com>"
          body: |
            **Mutation Summary:**
            ${{ steps.summary.outputs.mutation_summary }}

          delete-branch: false

      - name: Output PR info
        run: |
          echo "PR number: ${{ steps.pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.pr.outputs.pull-request-url }}"
