name: Mutation Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - test-main

permissions:
  contents: write
  pull-requests: write

jobs:
  pipeline:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Bodybuilders[bot]"
          git config user.email "bodybuilders[bot]@bodybuilders.com"

      - name: Merge test-main into test-mutation
        run: |
          git checkout test-mutation
          git merge --no-commit --no-ff origin/test-main || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scripts/mutator.py
        run: python scripts/mutator.py

      - name: Run scripts/fixer.py
        run: python scripts/fixer.py

      - name: Commit changes from mutator & fixer
        run: |
          git add .
          git commit -m "Changes from mutator.py and fixer.py" || echo "No changes to commit"
          git push origin test-mutation || echo "Nothing to push"

      - name: Create Pull Request to test-main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: test-main
          head: test-mutation
          branch: mutation-auto-pr-${{ github.run_number }}
          title: "Auto PR: Test-Mutation → Test-Main"
          body: |
            This PR was automatically created after running mutator.py and fixer.py.
